#!/usr/bin/env python3
"""Render the clinical knowledge pack into diffable bilingual review tables.

Fulfils the REVIEWER_BRIEF.md promise: reviewers get side-by-side
English/Burmese tables of every red-flag rule, vital rule, intake question,
and emergency string — each with an approve/correct row — without extracting
anything by hand.

Usage: python scripts/generate_reviewer_pack.py  (writes docs/REVIEWER_PACK.md)
"""

from __future__ import annotations

import json
import subprocess
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACK_PATH = ROOT / "src" / "ai_doctor" / "knowledge" / "v3" / "cardiometabolic_pack.json"
OUT_PATH = ROOT / "docs" / "REVIEWER_PACK.md"


def describe(item: dict) -> tuple[str, str]:
    """Human-readable (english, burmese) rendering of one pack rule."""
    if "terms" in item:  # red-flag symptom: list of EN+MY trigger phrases
        en_terms = [t for t in item["terms"] if all(ord(c) < 0x1000 for c in t)]
        my_terms = [t for t in item["terms"] if t not in en_terms]
        return "; ".join(en_terms), "; ".join(my_terms)
    if "threshold" in item:  # vital rule
        return (
            f"{item['kind']} {item['operator']} {item['threshold']} {item.get('unit', '')}".strip(),
            "",
        )
    # question / content entries carry bare en/my keys at top level
    if "en" in item or "my" in item:
        return str(item.get("en", "")), str(item.get("my", ""))
    label = item.get("label")
    if isinstance(label, dict):
        return str(label.get("en", "")), str(label.get("my", ""))
    if isinstance(label, str):
        return label, ""
    return json.dumps(item, ensure_ascii=False), ""


def row(num: int, label: str, en: str, my: str) -> list[str]:
    return [
        f"| {num} | {label} | {en} | {my} | ☐ approve | ☐ correct: |",
    ]


def main() -> None:
    pack = json.loads(PACK_PATH.read_text())
    commit = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, capture_output=True, text=True
    ).stdout.strip()

    lines: list[str] = [
        "# Reviewer Pack — bilingual clinical surface",
        "",
        f"Generated from `cardiometabolic_pack.json` @ `{commit}` on {date.today().isoformat()}.",
        f"Pack id: `{pack.get('pack_id')}` · release `{pack.get('release')}` · "
        f"`approved_for_clinical_use={pack.get('approved_for_clinical_use')}`.",
        "",
        "**Instruction:** for each row mark *approve*, or write the correction in the",
        "*correct* column (English or Burmese or both). Sign the statement at the end.",
        "",
    ]

    sections = [
        ("Red-flag symptoms", pack.get("red_flag_symptoms", [])),
        ("Home-vital rules", pack.get("vital_rules", [])),
        ("Guided-intake questions", pack.get("question_catalog", [])),
        ("Alert policies", pack.get("alert_policies", [])),
    ]
    counter = 0
    for title, items in sections:
        lines += [f"## {title}", "", "| # | id | English | မြန်မာ | approve | correct |", "|---|----|---------|-------|---------|---------|"]
        for item in items:
            counter += 1
            ident = item.get("id") or item.get("rule_id") or item.get("question_id") or "—"
            en, my = describe(item)
            lines += row(counter, f"`{ident}`", en.replace("|", "\\|"), my.replace("|", "\\|"))
        lines.append("")

    lines += [
        "## Reviewer statement (sign after marking every row above)",
        "",
        '```text',
        "I reviewed the rules marked above in this pack version only",
        f"(pack_id {pack.get('pack_id')}, release {pack.get('release')}, commit {commit}).",
        "This is a scope-limited content review, not an endorsement of the software.",
        "",
        "Name: ______________________  Role: ______________________",
        "Signature: ____________________  Date: ____________",
        "```",
        "",
        "---",
        "Machine-generated by `scripts/generate_reviewer_pack.py`; regenerate after any pack change.",
    ]

    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_PATH.relative_to(ROOT)} ({counter} rows)")


if __name__ == "__main__":
    main()
